repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-added-large-files
  # - repo: https://github.com/hadolint/hadolint
  #   rev: v2.7.0 (tag is broken)
  #   hooks:
  #     - id: hadolint-docker
