name: build image

on:
  push:
    branches:
      - main
      - nightlies
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: redhat-actions/buildah-build@v2
      id: build-image
      with:
        image: whynothugo/makepkg
        tags: latest ${{ github.sha }}
        containerfiles: |
          ./Dockerfile

    - uses: redhat-actions/push-to-registry@v2
      if: ${{ github.ref == 'refs/heads/nightlies' }}
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: docker.io
        username: whynothugo
        password: ${{ secrets.REGISTRY_PASSWORD }}
