name: Trigger nighly rebuilds

on: 
  schedule:
    - cron:  '0 0 * * *'

jobs:
  rebuild:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Trigger nightly
        run: curl $NIGHTLY_WEBHOOK
